"""Application configuration."""

from .settings import (
    APP_VERSION,
    APP_TITLE,
    APP_ICON,
    WOM_API_BASE,
    WOM_GROUP_ID,
    WOM_USER_AGENT,
    CACHE_TTL_MEMBERS,
    CACHE_TTL_GAINS,
    CACHE_TTL_HISCORES,
    CACHE_TTL_DETAILS,
    ACTIVITY_THRESHOLDS,
    ACTIVITY_COLORS,
    GAIN_PERIODS,
    DEFAULT_GAIN_PERIOD,
    SKILLS,
    COMBAT_SKILLS,
)

__all__ = [
    'APP_VERSION',
    'APP_TITLE',
    'APP_ICON',
    'WOM_API_BASE',
    'WOM_GROUP_ID',
    'WOM_USER_AGENT',
    'CACHE_TTL_MEMBERS',
    'CACHE_TTL_GAINS',
    'CACHE_TTL_HISCORES',
    'CACHE_TTL_DETAILS',
    'ACTIVITY_THRESHOLDS',
    'ACTIVITY_COLORS',
    'GAIN_PERIODS',
    'DEFAULT_GAIN_PERIOD',
    'SKILLS',
    'COMBAT_SKILLS',
]
